### ISSUE TITLE
publish new version with CFRunLoop

### ISSUE THREAD

**Issue by forticulous** [dcuddeback/core-foundation-sys#7]
Hey @dcuddeback, I'm interested in making use of the CFRunLoop stuff that was just added recently. I was wondering if you could publish a new version of this crate with that included?

**Comment by ticky** [comment]
0.1.3 also seems to be broken currently, I get lots of errors about `base::CF` types being private (I’m _actually_ using iokit-sys, a dependent library), a new release would be great!

**Comment by dcuddeback** [comment]
I'll try to get to this this weekend. I have to work today, and unfortunately this doesn't relate to my paid work, so it will have to wait until I have some free time.

**Comment by dcuddeback** [comment]
v0.1.4 is released. Thank you for being patient.
